# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: TICS static code analysis

on:
  schedule:
    - cron: '0 2 * * 6' # Every Saturday 2:00 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  tiobe-scan:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Activate virtual environment and install dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install flake8 poetry pylint pytest tox
          poetry install --all-groups
          echo PATH="$PATH" >> "$GITHUB_ENV"

      - name: Run tox tests to create coverage.xml
        run: tox run -e unit

      - name: Move results to necessary folder for TICS
        run: |
          mkdir -p cover
          mv coverage.xml cover/coverage.xml

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: valkey-operator
          branchdir: ${{ env.GITHUB_WORKSPACE }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          calc: ALL
    permissions: {}